# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 87b9e70d507490533ae8e07b0f589dc45be3a5b2464483ad60456e837129e7cf246c1b33f3b9d6df459166870febeaa782c07ae9dd29793bffea55fdd0539c74

test:
  secret_key_base: 3189b176d164b620b5dacf56399a80da5b7109588714d696f947326689e14ce36473dc3ac15f253bc8fef297d5db870fc669548bf7c545ffc500358f8800e251

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
